In [1]:
import h5py
import matplotlib.pyplot as plt
from os import listdir
from mpl_toolkits import mplot3d
import matplotlib.gridspec as gridspec
import numpy as np
import re

axisScale = 0.03
datasets = ['organic', 'gm_late', 'gm_early']

for dataset in datasets:
    print('-----------------------------------------')
    print(dataset)
    print('-----------------------------------------')
    
    files = listdir('data/' + dataset)

    count = 0

    galaxyAm = np.array(range(96), dtype=float).reshape(24,4)
    
    for file in files:
        
        # get redshift from the filename
        m = re.search('(z[0-9])\w+', file)
        s = m.group(0).replace('z', '')
        s = s.replace('p', '.')
        redshift = float(s)
        
        # load data for a particular galaxy at a particular redshift
        f = h5py.File('data/' + dataset + '/' + file,'r')

        # extract data from the file
        ds_c = f['Coordinates']
        ds_v = f['Velocity']
        ds_m = f['Mass']

        # Calculate the resultant angular momentum vectors r
        # r contains the AM vectors for each particle per redshift era
        r0 = np.cross(ds_c, ds_v)
        r = np.transpose(np.multiply(ds_m, np.transpose(r0)))
        print ("shape r", np.shape(r))
        
        # Calculate the total angular momentum vector by summing the vectors (per redshift epoch)
        angMomTot = np.sum(r, axis=0)
        print ("shape angMomTot", np.shape(angMomTot)) 
        
        # Calculate the magnitude of the total angular momentum vector for each redshift epoch
        # We use this to normalise the angular momentum to a unit vector for scaling during the transform
        magnitude = np.linalg.norm(angMomTot)
        
        # Alternative way of calculating the magnitude
        # magnitude2 = np.sqrt(angMomTot[0]**2 + angMomTot[1]**2 + angMomTot[2]**2)
        
        # Calculate the scale factor by working out the angular momentum 
        unitVect_z = angMomTot / magnitude
        #print ("unitVect_z", unitVect_z)
        #print ("np.linalg.norm(unitVect_z)", np.linalg.norm(unitVect_z))
        
        
        # the angular momentum's vector's (unitVect_z) direction is directly out of the plane of the galaxy
        # unitVect_z = k, but j = [-k2/k1, 1, 0], so
        
        k = unitVect_z
        print ("k: ", k)
        
        j = [k[1]/k[0], 1, 0]
        print ("j: ", j)
        
        i = np.cross(j, unitVect_z)
        print ("i: ", i)
   
        dsc_x_trsfrm = np.dot(ds_c, i)
        print ("dsc_x_trsfrm", dsc_x_trsfrm)
        print ("dsc_x_trsfrm shape", np.shape(dsc_x_trsfrm))
        
        dsc_y_trsfrm = np.dot(ds_c, j)
        print ("dsc_y_trsfrm", dsc_y_trsfrm)
        print ("dsc_y_trsfrm shape", np.shape(dsc_y_trsfrm))
        
        dsc_z_trsfrm = np.dot(ds_c, k)
        print ("dsc_z_trsfrm", dsc_z_trsfrm)
        print ("dsc_z_trsfrm shape", np.shape(dsc_z_trsfrm))
        
        #dsc_trans = list(zip(dsc_x_trsfrm, dsc_y_trsfrm, dsc_z_trsfrm))
        dsc_trans = np.transpose(np.array([dsc_x_trsfrm, dsc_y_trsfrm, dsc_z_trsfrm]))
        
        print ("dsc_trans", dsc_trans)
        print ("dsc_trans shape", np.shape(dsc_trans))
        
        print ("dsc_trans[0,x]")
        print (dsc_trans[0,0])
        print ("dsc_trans[0,y]")
        print (dsc_trans[0,1])
        print ("dsc_trans[0,z]")
        print (dsc_trans[0,2])        

        # Store totals of all particles for each redshift in the current galaxy
        #galaxyAm[count, 0] = redshift
        #galaxyAm[count, 1] = r[]
              
        count = count + 1
        print ('-------------------------------------------------')
    
    # print each angular momentum component's total per redshift
    #for n in range(24):
    #    print('Galaxy "' + dataset + '" redshift: ' + str(galaxyAm[n][3]) + '\t total:  k1:' + str(galaxyAm[n][0]) + '\t k2:' + str(galaxyAm[n][1]) + '\t k3:' + str(galaxyAm[n][2]))
    #    print('Galaxy "' + dataset + '" redshift: ' + str(galaxyAm[n][0]) + '\t j1: ' + (str(-galaxyAm[n][1] / galaxyAm[n][0]))) + "\t normalised: "
              
    #print ('length: ' + str(np.shape(galaxyAm)[0]))
    #plt.plot(galaxyAm[0:,3], galaxyAm[0:,2])
    #plt.plot(galaxyAm[0:,0], galaxyAm[0:,1])

    #plt.title('Galaxy: ' + dataset + ' - Magnitude of Angular Momentum vs. Redshift', pad=30)
    #plt.xlabel('Redshift')
    #plt.ylabel(r'L Magnitude ($M_\odot\ Mpc km s^{-1})$')
    #plt.ticklabel_format(axis='y', style='sci', useMathText=True)
    #plt.rcParams["figure.figsize"] = (12,10)
    #plt.semilogy()
    #plt.show()    

-----------------------------------------
organic
-----------------------------------------
shape r (34, 3)
shape angMomTot (3,)
k:  [0.9515281  0.30598536 0.0311003 ]
j:  [0.32157258995097276, 1, 0]
i:  [ 0.0311003 -0.010001  -0.8531316]
dsc_x_trsfrm [ 6.13998190e-05  1.65115523e-04  8.77937846e-05  8.99734131e-05
  2.69702998e-04  4.83208424e-05  3.54389382e-04 -3.00953626e-04
 -3.15812632e-04 -5.70459763e-05 -7.03923517e-04 -9.70472194e-04
 -2.21166245e-04 -1.15341801e-04 -2.53128237e-04  2.37669103e-04
  1.71834966e-04  1.38543890e-04  8.92746522e-06  1.00262623e-04
  3.72887136e-04  2.29460923e-04  5.60418005e-04 -5.33377058e-04
 -7.18491686e-04  1.10032031e-04 -1.54254355e-04 -2.20771756e-04
  1.85007711e-04 -1.70436654e-04  1.70208434e-05 -7.52118921e-05
 -9.99800039e-05 -3.99353344e-04]
dsc_x_trsfrm shape (34,)
dsc_y_trsfrm [ 4.22640480e-04  3.52933576e-04  5.44728581e-04 -4.23305190e-04
 -2.88945931e-04 -1.60526779e-04 -1.87470851e-04 -2.54519642e-04
 -7.49201637e-05 -1.832251

shape r (44360, 3)
shape angMomTot (3,)
k:  [ 0.33754953  0.3880109  -0.85761755]
j:  [1.1494932410732626, 1, 0]
i:  [-0.85761755  0.98582557  0.10846638]
dsc_x_trsfrm [-0.00029271 -0.00030481 -0.00030333 ...  0.00027526  0.00029079
  0.00029525]
dsc_x_trsfrm shape (44360,)
dsc_y_trsfrm [0.00038542 0.0003893  0.00038732 ... 0.00012906 0.00018154 0.00019957]
dsc_y_trsfrm shape (44360,)
dsc_z_trsfrm [-7.03563399e-05 -5.50554697e-05 -6.05235715e-05 ... -6.64702755e-05
 -7.37365782e-05 -7.35728386e-05]
dsc_z_trsfrm shape (44360,)
dsc_trans [[-2.92713033e-04  3.85417346e-04 -7.03563399e-05]
 [-3.04805264e-04  3.89304368e-04 -5.50554697e-05]
 [-3.03326796e-04  3.87324413e-04 -6.05235715e-05]
 ...
 [ 2.75260748e-04  1.29060342e-04 -6.64702755e-05]
 [ 2.90785661e-04  1.81538118e-04 -7.37365782e-05]
 [ 2.95249280e-04  1.99572797e-04 -7.35728386e-05]]
dsc_trans shape (44360, 3)
dsc_trans[0,x]
-0.00029271303283319265
dsc_trans[0,y]
0.0003854173464541729
dsc_trans[0,z]
-7.035633994495607e-05
-----

dsc_trans [[-7.56801521e-04  9.65322445e-04 -6.63646037e-05]
 [-8.06060140e-04  9.48310267e-04 -6.53392353e-05]
 [-8.06971646e-04  9.96109122e-04 -9.60581869e-05]
 ...
 [ 3.69504285e-03  2.16014938e-03  1.17039105e-03]
 [ 3.90701182e-03  1.81574563e-03  1.17995896e-03]
 [ 3.62316148e-03  1.14418535e-03  8.47044408e-04]]
dsc_trans shape (90824, 3)
dsc_trans[0,x]
-0.000756801520924367
dsc_trans[0,y]
0.0009653224449876363
dsc_trans[0,z]
-6.636460370246208e-05
-------------------------------------------------
-----------------------------------------
gm_late
-----------------------------------------
shape r (29, 3)
shape angMomTot (3,)
k:  [-0.4505637  -0.67027346 -0.58968282]
j:  [1.4876330763188532, 1, 0]
i:  [-0.58968282  0.87723167 -0.54655728]
dsc_x_trsfrm [ 2.37618524e-04  4.01861895e-05  2.89458461e-05 -2.14910526e-04
 -9.06657845e-04 -6.93078639e-05 -6.48206142e-04 -1.58627621e-03
 -2.14700430e-03 -1.09648684e-03  4.48476774e-04  8.51012837e-04
  1.19556634e-03 -1.19219699e-03 -1.0

dsc_x_trsfrm [-2.26351984e-02 -7.49302885e-02 -6.86231768e-02 -6.29002139e-02
 -2.94373507e-02 -5.59173387e-02 -4.11817385e-02 -1.15178222e-02
 -3.27580753e-02 -2.38633581e-02 -2.48200617e-02 -2.35246917e-02
 -2.33923791e-02 -4.04445578e-02 -3.65457886e-02 -4.86162107e-02
 -4.25762329e-02 -4.16128208e-02 -3.13639228e-02 -3.08014781e-02
 -4.12877252e-02 -3.73072723e-02 -4.76924420e-02 -4.91437076e-02
 -5.13101375e-02 -4.18151080e-02 -5.03599507e-02 -2.58399931e-02
 -2.65799730e-02 -3.14027343e-02 -2.40589758e-02 -2.69908518e-02
 -3.07264551e-02 -2.48243381e-02 -2.84826981e-02 -4.22706766e-02
 -4.67195330e-02 -4.76439892e-02 -3.82807835e-02 -3.30310992e-02
 -3.58294988e-02 -1.97986670e-02 -3.12639975e-02 -2.78841989e-02
 -2.43772452e-02 -2.32207040e-02 -1.97495560e-02 -1.93144258e-02
 -2.30658030e-02 -2.40309862e-02 -2.12843253e-02 -2.63465501e-02
 -2.19572358e-02 -2.45217765e-02 -2.43312389e-02 -2.07813238e-02
 -1.06809426e-01 -1.11287385e-01 -9.87991207e-02 -8.84194338e-02
 -4.53263026

dsc_z_trsfrm [-0.00090608 -0.0009903  -0.00154501 ...  0.00183384  0.00189922
  0.00193354]
dsc_z_trsfrm shape (3273,)
dsc_trans [[-0.00115314 -0.00118123 -0.00090608]
 [-0.00133034 -0.00130493 -0.0009903 ]
 [-0.00152818 -0.00239326 -0.00154501]
 ...
 [-0.00033392  0.00214688  0.00183384]
 [-0.00043914  0.00222563  0.00189922]
 [-0.00036513  0.00213313  0.00193354]]
dsc_trans shape (3273, 3)
dsc_trans[0,x]
-0.0011531415582961065
dsc_trans[0,y]
-0.0011812319981429854
dsc_trans[0,z]
-0.0009060787842456023
-------------------------------------------------
shape r (21843, 3)
shape angMomTot (3,)
k:  [ 0.59239507 -0.65443832  0.4698708 ]
j:  [-1.104732896713157, 1, 0]
i:  [0.4698708  0.51908173 0.13058447]
dsc_x_trsfrm [4.63455051e-05 6.94022893e-05 1.36788934e-04 ... 1.98103601e-03
 1.87677765e-03 2.17017654e-03]
dsc_x_trsfrm shape (21843,)
dsc_y_trsfrm [-2.17591304e-04  8.85624286e-05  1.17595840e-04 ...  2.25413984e-03
  1.98799113e-03  2.35538913e-03]
dsc_y_trsfrm shape (21843,)
dsc_z_t

shape r (53481, 3)
shape angMomTot (3,)
k:  [ 0.06899975  0.35772439 -0.93127455]
j:  [5.184430043627951, 1, 0]
i:  [-0.93127455  4.82812777  1.78559735]
dsc_x_trsfrm [0.06111698 0.06798277 0.06222898 ... 0.00903624 0.00990735 0.01097668]
dsc_x_trsfrm shape (53481,)
dsc_y_trsfrm [0.03528316 0.02285317 0.01686443 ... 0.01395463 0.01209436 0.01180513]
dsc_y_trsfrm shape (53481,)
dsc_z_trsfrm [ 1.73445349e-02  1.58192003e-02  1.51209700e-02 ... -9.27418480e-05
 -1.37469908e-04 -2.22351343e-04]
dsc_z_trsfrm shape (53481,)
dsc_trans [[ 6.11169797e-02  3.52831622e-02  1.73445349e-02]
 [ 6.79827746e-02  2.28531658e-02  1.58192003e-02]
 [ 6.22289829e-02  1.68644313e-02  1.51209700e-02]
 ...
 [ 9.03623554e-03  1.39546251e-02 -9.27418480e-05]
 [ 9.90735196e-03  1.20943608e-02 -1.37469908e-04]
 [ 1.09766820e-02  1.18051258e-02 -2.22351343e-04]]
dsc_trans shape (53481, 3)
dsc_trans[0,x]
0.06111697970653165
dsc_trans[0,y]
0.03528316220675876
dsc_trans[0,z]
0.017344534867718916
---------------------