In [4]:
import h5py
import matplotlib.pyplot as plt
from os import listdir
from mpl_toolkits import mplot3d
import matplotlib.gridspec as gridspec
import numpy as np
import re

axisScale = 0.03
datasets = ['organic', 'gm_late', 'gm_early']

for dataset in datasets:
    print('-----------------------------------------')
    print(dataset)
    print('-----------------------------------------')
    
    files = listdir('data/' + dataset)

    count = 0

    galaxyAm = np.array(range(96), dtype=float).reshape(24,4)
    
    for file in files:
    #if 1==1:



        #file = 'star_particles_015_z002p012.hdf5'
        #file = 'star_particles_028_z000p000.hdf5'
        
        # get redshift from the filename
        m = re.search('(z[0-9])\w+', file)
        s = m.group(0).replace('z', '')
        s = s.replace('p', '.')
        redshift = float(s)
        
        # load data for a particular galaxy at a particular redshift
        f = h5py.File('data/' + dataset + '/' + file,'r')

        # extract date from the file
        ds_c = f['Coordinates']
        ds_v = f['Velocity']
        ds_m = f['Mass']
    

        # Calculate the resultant angular momentum vectors r
        # r contains the AM vectors for each particle per redshift era
        r0 = np.cross(ds_c, ds_v)
        r = np.transpose(np.multiply(ds_m, np.transpose(r0)))
        print (np.shape(r))
        
        # Calculate the total angular momentum vector by summing the vectors (per redshift epoch)
        angMomTot = np.sum(r, axis=0)
        print (np.shape(angMomTot)) 
        
        # Calculate the magnitude of the total angular momentum vector for each redshift epoch
        magnitude = np.linalg.norm(angMomTot)
        print (magnitude)
        
        # Alternative way of calculating the magnitude
        # magnitude2 = np.sqrt(angMomTot[0]**2 + angMomTot[1]**2 + angMomTot[2]**2)
        
        # Calculate the scale factor by working out the angular momentum 
        unitVect_z = angMomTot / magnitude
        print (unitVect_z)
        print (np.linalg.norm(unitVect_z))

        #angMomTot2 = 
        #print ("angMomTot: ", file, angMomTot)
        #rTot = rTot + r

        # Store totals of all particles for each redshift in the current galaxy
        galaxyAm[count, 0] = redshift
        #galaxyAm[count, 1] = r[]
              
        count = count + 1
        print ('-------------------------------------------------')
    
    # print each angular momentum component's total per redshift
    for n in range(24):
        print('Galaxy "' + dataset + '" redshift: ' + str(galaxyAm[n][3]) + '\t total:  k1:' + str(galaxyAm[n][0]) + '\t k2:' + str(galaxyAm[n][1]) + '\t k3:' + str(galaxyAm[n][2]))
        print('Galaxy "' + dataset + '" redshift: ' + str(galaxyAm[n][0]) + '\t j1: ' + (str(-galaxyAm[n][1] / galaxyAm[n][0]))) + "\t normalised: "
              
    #print ('length: ' + str(np.shape(galaxyAm)[0]))
    #plt.plot(galaxyAm[0:,3], galaxyAm[0:,2])
    plt.plot(galaxyAm[0:,0], galaxyAm[0:,1])

    plt.title('Galaxy: ' + dataset + ' - Magnitude of Angular Momentum vs. Redshift', pad=30)
    plt.xlabel('Redshift')
    plt.ylabel(r'L Magnitude ($M_\odot\ Mpc km s^{-1})$')
    plt.ticklabel_format(axis='y', style='sci', useMathText=True)
    plt.rcParams["figure.figsize"] = (12,10)
    plt.semilogy()
    plt.show()    

-----------------------------------------
organic
-----------------------------------------
(34, 3)
(3,)
107118.16893205802 107118.16893205802
[0.9515281  0.30598536 0.0311003 ]
1.0
-------------------------------------------------
(56, 3)
(3,)
1302369.286120002 1302369.286120002
[ 0.65267355 -0.15264495  0.74210293]
1.0
-------------------------------------------------
(129, 3)
(3,)
2373041.7883347273 2373041.7883347273
[ 0.28733915  0.50012508 -0.81689113]
1.0
-------------------------------------------------
(144, 3)
(3,)
681662.0588077805 681662.0588077805
[-0.0927266   0.99391521  0.05945022]
0.9999999999999999
-------------------------------------------------
(158, 3)
(3,)
2451548.7431655293 2451548.7431655293
[-0.10765651  0.98838324 -0.10727835]
1.0
-------------------------------------------------
(221, 3)
(3,)
1717913.4703316444 1717913.4703316444
[0.80910861 0.42998242 0.40057256]
1.0
-------------------------------------------------
(305, 3)
(3,)
4929184.66131151 4929184.66

TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'